name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: |
          git clone https://github.com/olOwOlo/hugo-theme-even themes/even
          hugo --minify
      
      - name: Deploy
        run: |
          pwd
          ls -lrt
        # uses: easingthemes/ssh-deploy@v2.0.7
        # env:
        #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #   ARGS: "-avz --delete"
        #   SOURCE: "public/*"
        #   REMOTE_HOST: "zxslinux.world"
        #   REMOTE_USER: "root"
        #   TARGET: "/usr/local/nginx/html/"